spring:
  messages.basename: messages, error

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://myboard-database2.cs4usf0xv8ru.ap-northeast-2.rds.amazonaws.com:3306/myboard_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: DDolchu0410!

  #  datasource:
#    url: jdbc:mysql://myboard-db.cs4usf0xv8ru.ap-northeast-2.rds.amazonaws.com:3306/myboard
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: admin
#    password: DDolchu0410

security:
  oauth2:
    client:
      registration:
        google:
          client-id: 932429101354-j73loi8m64qhkm5vpenmak7ih1h2c1a2.apps.googleusercontent.com
          client-secret: q5j64IA4KOpbEbMLz4MvrT7C
          scope:
            - email
            - profile

        facebook:
          client-id: 184494353207222
          client-secret: a56d23db48b45ba2645d23b003fb4460
          scope:
            - email
            - public_profile

        naver:
          client-id: fCHnhxb3MLolrXsxCGGQ
          client-secret: IywLuOew5K
          scope:
            - id
            - email
            - name
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8080/login/oauth2/code/naver
          client-name: Naver

        kakao:
          client-id:  6c59b4dda916bc7b5a99d658afc58a07
          client-secret:
          scope:
            - account_email
            - profile
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8080/login/oauth2/code/kakao
          client-name: Kakao
          client-authentication-method: POST

      provider:
        naver:
          authorization-uri:  https://nid.naver.com/oauth2.0/authorize
          token-uri:  https://nid.naver.com/oauth2.0/token
          user-info-uri:  https://openapi.naver.com/v1/nid/me
          user-name-attribute: response
        kakao:
          authorization-uri:  https://kauth.kakao.com/oauth/authorize
          token-uri:  https://kauth.kakao.com/oauth/token
          user-info-uri:  https://kapi.kakao.com/v2/user/me
          user-name-attribute: id

  jpa:
#    open-in-view: true
    database-platform: mysql
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.PhysicalNamingStrategyStandardImpl
        format_sql: true
        show_sql: true
#    defer-datasource-initialization: true

  servlet.multipart:
    maxFileSize: 10MB
    maxRequestSize: 20MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true
#jwt:
#  header: Authorization
#  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
#  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
#  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#  token-validity-in-seconds: 86400

logging:
  exception-conversion-word: '%wEx'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}){green} %clr([%22thread]){magenta} %clr(%-40.40logger{39}){cyan} %clr(: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
  level:
    #    root: debug
    web: debug